#!/usr/bin/env node
// Copyright (c) 2026 Rational Mystic LLC. PolyForm Noncommercial 1.0.0 — see LICENSE.md
// Import a .pack.json back into a directory pack.
//
//   node scripts/pack-import.mjs my-course.pack.json
//   node scripts/pack-import.mjs my-course.pack.json build/my-course
//
// A .pack.json does not have to be converted to be used — `shellgrounds validate
// ./my-course.pack.json` reads it directly, and so does the loader. Import
// exists for the author who wants to keep working on the pack the way the
// three shipped packs are laid out: one file per concern, diffable, greppable.
//
// THE RULE THIS FILE OBEYS: it never writes JavaScript derived from pack data.
// It writes `fs.linux.json` (the author's data) plus a FIXED four-line loader
// whose text does not depend on anything in the pack except the pack's own
// name. There is no template hole an author could fill with code.

import { writeFile, mkdir, readFile, access } from 'node:fs/promises';
import { join, resolve, relative, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import {
  loadPackFile, validatePackFileStructure, stripComments, assertNoCode, PackFormatError
} from '../packages/engine/validate/packFile.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const PACK_FILE_MODULE = resolve(HERE, '../packages/engine/validate/packFile.js');

const pascal = (id) => String(id)
  .split(/[^a-zA-Z0-9]+/)
  .filter(Boolean)
  .map((w) => w[0].toUpperCase() + w.slice(1))
  .join('');

const displayPath = (p) => {
  const rel = relative(process.cwd(), p);
  return (!rel || rel.startsWith('..')) ? p : rel;
};

const exists = async (p) => { try { await access(p); return true; } catch { return false; } };

/** The generated loader. Only the pack name and platform vary; the code does not. */
function loaderStub(packId, platform, importPath) {
  const fnName = `create${pascal(packId)}${platform === 'windows' ? 'Windows' : ''}Filesystem`;
  return `// GENERATED by \`shellgrounds import\`. Do not edit.
//
// The pack's filesystem lives in fs.${platform}.json as data. This file exists only
// because packs/index.js imports a function. Its four lines are fixed: nothing
// an author writes reaches this file, so importing a pack never adds code.
import { expandFilesystem } from '${importPath}';
import tree from './fs.${platform}.json' with { type: 'json' };

export function ${fnName}() {
  return expandFilesystem(tree, { isWindows: ${platform === 'windows'} });
}
`;
}

function registrySnippet(packId, platforms) {
  const P = pascal(packId);
  const lines = [
    `import ${P}PackJson from './${packId}/pack.json' with { type: 'json' };`,
    `import ${P}Challenges from './${packId}/challenges.json' with { type: 'json' };`
  ];
  for (const plat of platforms) {
    const fn = `create${P}${plat === 'windows' ? 'Windows' : ''}Filesystem`;
    lines.push(`import { ${fn} } from './${packId}/fs.${plat}.js';`);
  }
  const createFs = platforms.length > 1
    ? `(platform) => platform === 'windows' ? create${P}WindowsFilesystem() : create${P}Filesystem()`
    : `() => create${P}Filesystem()`;
  lines.push('');
  lines.push('// ...then add to the PACKS object:');
  lines.push(`  '${packId}': {`);
  lines.push(`    id: '${packId}',`);
  lines.push(`    manifest: ${P}PackJson,`);
  lines.push(`    challenges: ${P}Challenges,`);
  lines.push('    help: {},');
  lines.push('    commands: {},');
  lines.push(`    createFs: ${createFs}`);
  lines.push('  },');
  return lines.join('\n');
}

/**
 * @returns {{ outDir: string, written: string[], packId: string, warnings: string[], registrySnippet: string }}
 */
export async function importPack(filePath, outDir = null, options = {}) {
  const text = await readFile(resolve(filePath), 'utf8');
  let raw;
  try {
    raw = JSON.parse(text);
  } catch (err) {
    throw new PackFormatError(`${filePath} is not valid JSON: ${err.message}`);
  }
  assertNoCode(raw, '$');
  const clean = stripComments(raw);
  const { errors, warnings } = validatePackFileStructure(clean);
  if (errors.length) {
    throw new PackFormatError(`Refusing to import an invalid pack file:\n  - ${errors.join('\n  - ')}`);
  }
  // Load it too: this proves the filesystem actually expands before anything is
  // written, so a bad tree fails with nothing half-created on disk.
  const pack = loadPackFile(clean);
  const platforms = pack.manifest.platforms || ['linux'];
  for (const plat of platforms) pack.createFs(plat);

  const dir = resolve(outDir || join('packs', pack.id));
  if (await exists(dir) && !options.force) {
    throw new PackFormatError(
      `${dir} already exists. Pass a different output directory, or --force to overwrite it.`
    );
  }
  await mkdir(dir, { recursive: true });

  const written = [];
  const put = async (name, content) => {
    await writeFile(join(dir, name), content, 'utf8');
    written.push(name);
  };
  const putJson = (name, value) => put(name, `${JSON.stringify(value, null, 2)}\n`);

  const manifest = {
    ...clean.manifest,
    id: pack.id,
    acts: clean.acts ?? clean.manifest?.acts ?? [],
    badges: clean.badges ?? clean.manifest?.badges ?? []
  };
  await putJson('pack.json', manifest);
  await putJson('challenges.json', clean.challenges);
  if (clean.help && Object.keys(clean.help).length) await putJson('help.json', clean.help);
  if (clean.commands && Object.keys(clean.commands).length) await putJson('commands.json', clean.commands);

  let importPath = relative(dir, PACK_FILE_MODULE).split('\\').join('/');
  if (!importPath.startsWith('.')) importPath = `./${importPath}`;

  for (const plat of platforms) {
    await putJson(`fs.${plat}.json`, clean.filesystems[plat]);
    await put(`fs.${plat}.js`, loaderStub(pack.id, plat, importPath));
  }

  const snippet = registrySnippet(pack.id, platforms);
  await put('README.md', [
    `# ${manifest.name || pack.id}`,
    '',
    `Imported from a \`.pack.json\` (format version ${clean.formatVersion}).`,
    '',
    '| File | What it is |',
    '|---|---|',
    '| `pack.json` | the manifest: name, platforms, theme, acts, badges |',
    '| `challenges.json` | every challenge, in order |',
    ...platforms.map((p) => `| \`fs.${p}.json\` | the ${p} filesystem, as data |`),
    ...platforms.map((p) => `| \`fs.${p}.js\` | a generated four-line loader; do not edit |`),
    '',
    '## Check it',
    '',
    '```bash',
    `node bin/shellgrounds.js validate ${displayPath(dir)}`,
    '```',
    '',
    '## Put it in the app',
    '',
    'The registry is still hand-edited. Add this to `packs/index.js`:',
    '',
    '```js',
    snippet,
    '```',
    '',
    'See `docs/PACK-FORMAT.md` for every field, and `packs/AUTHORING.md` for the tutorial.',
    ''
  ].join('\n'));

  return { outDir: dir, written, packId: pack.id, warnings, registrySnippet: snippet, platforms };
}

async function main() {
  const args = process.argv.slice(2).filter((a) => a !== '--force');
  const force = process.argv.includes('--force');
  const [file, out] = args;
  if (!file) {
    console.error('Usage: node scripts/pack-import.mjs <file.pack.json> [outDir] [--force]');
    process.exit(1);
  }
  const r = await importPack(file, out, { force });
  for (const w of r.warnings) console.warn(`warning: ${w}`);
  console.log(`Imported ${r.packId} -> ${r.outDir}`);
  for (const name of r.written) console.log(`  ${name}`);
  console.log('');
  console.log(`Validate it:  node bin/shellgrounds.js validate ${displayPath(r.outDir)}`);
  console.log('To show it in the app, add the snippet in that directory\'s README.md to packs/index.js.');
}

if (import.meta.url === pathToFileURL(process.argv[1] || '').href) {
  main().catch((err) => { console.error(err.message); process.exit(1); });
}
